//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlgoExpiry
    {
        public int Id { get; set; }
        public string DateExpiry { get; set; }
        public string DeviceID { get; set; }
        public int CustomerID { get; set; }
        public string AppName { get; set; }
        public string MaxUser { get; set; }
    }
}
